# Generated by Django 5.1.1 on 2024-10-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymenthistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
    ]
