# Generated by Django 5.1.1 on 2024-10-01 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_subscription_unique_together'),
        ('video', '0003_remove_videomodel_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'video')},
        ),
    ]
