# Generated by Django 5.1.1 on 2024-10-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_watchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='is_paid',
        ),
    ]
