# Generated by Django 5.1.1 on 2024-10-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_comment_video_rating_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoStatus',
        ),
    ]
